#global config
global:
  scrape_interval:     1s
  evaluation_interval: 5s
  scrape_timeout:     1s
  #query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s
    static_configs:
      - targets: ['0.0.0.0:2112']
