---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-cdc
  namespace: monitoring
  labels: &labels
    org.service.project: common
    org.service.name: debezium-cdc
    org.service.entity: default
    org.service.environment: testing
spec:
  progressDeadlineSeconds: 120
  selector:
    matchLabels: *labels
  replicas: 1
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: debezium
          image: ${DEPLOY_IMAGE}
          ports:
            - name: debezium
              containerPort: 8083
            - name: metrics
              containerPort: 9012
            - name: metrics-jmx
              containerPort: 9000
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "1"
              memory: 1024Mi
          env:
            - name: JMXPORT
              value: '9013'
            - name: JMXHOST
              value: '0.0.0.0'
            - name: KAFKA_OPTS
              value: '-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=9000:/kafka/etc/config.yml'
            - name: BOOTSTRAP_SERVERS
              value: 'host-of-redpanda:9092'
            - name: LOG_LEVEL
              value: 'ERROR'
            - name: CONFIG_STORAGE_TOPIC
              value: 'inventory.configs'
            - name: GROUP_ID
              value: "1"
            - name: OFFSET_STORAGE_TOPIC
              value: 'inventory.offset'
            - name: STATUS_STORAGE_TOPIC
              value: 'inventory.status'
        - name: kowl-ui
          image: quay.io/cloudhut/kowl:master
          env:
            - name: KAFKA_BROKERS
              value: host-of-redpanda:9092
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
            requests:
              cpu: "0.1"
              memory: 64Mi
      terminationGracePeriodSeconds: 15
